blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/kolirt/laravel-telegram?tab=readme-ov-file#laravel-telegram
    about: Check the documentation for guides and examples.