name: 💬 Question
description: Ask a question about the kolirt/laravel-telegram.
title: '[Question]: '
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Before asking a question, please make sure that you have read through our [documentation](https://github.com/kolirt/laravel-telegram?tab=readme-ov-file#laravel-telegram) and existing [issues](https://github.com/kolirt/laravel-telegram/issues).
  - type: input
    id: version
    attributes:
      label: Package version
      description: |
        Leave blank if you have not yet configured the package and have not used it.
      placeholder: v1.0.0
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true